### ISSUE TITLE
Does it work for international train stations / Thalys / Eurostar?

### ISSUE THREAD

**Issue by coisnepe** [tducret/trainline-python#1]
Hey,

I tried to query for prices between Paris and Antwerp but got the following error:

```
➜  trainline_cli.py -d Paris -a Antwerpen-Centraal -n 3d
Traceback (most recent call last):
  File "/usr/local/bin/trainline_cli.py", line 92, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/trainline_cli.py", line 63, in main
    to_date=to_date)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 567, in search
    folders = _get_folders(search_results_obj=j)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 618, in _get_folders
    trip_obj_list = _get_trips(search_results_obj)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 651, in _get_trips
    segment_obj_list = _get_segments(search_results_obj)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 694, in _get_segments
    comfort_class_obj_list = _get_comfort_classes(search_results_obj)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 766, in _get_comfort_classes
    comfort_class_obj = ComfortClass(dict_comfort_class)
  File "/usr/local/lib/python3.7/site-packages/trainline/__init__.py", line 452, in __init__
    expected_type, expected_param, type(param_value)))
TypeError: Type <class 'dict'> expected for options, <class 'NoneType'> received

```

**Comment by tducret** [comment]
Hi @coisnepe 
I found the bug. A field (`options`) was missing for some belgian trains.
I just commited the fix.
I'll release `trainline` package `v0.0.5` in a few minutes.
You'll just have to `pip3 install --upgrade trainline`
