### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by qcha41** [tducret/trainline-python#2]
* trainline version: 0.06
* Python version: 3.7.1
* Operating System: win 10 64bits anaconda (package installé en pip)

### Description

Quand je run l'exemple 

```
# -*- coding: utf-8 -*-
import trainline

results = trainline.search(
	departure_station="Toulouse",
	arrival_station="Bordeaux",
	from_date="15/10/2018 08:00",
	to_date="15/10/2018 21:00")

print(results.csv())
```
j'obtiens 

```runfile('C:/Users/qchat/Desktop/test.py', wdir='C:/Users/qchat/Desktop')
Traceback (most recent call last):

  File "<ipython-input-12-7e6daafd5aef>", line 1, in <module>
    runfile('C:/Users/qchat/Desktop/test.py', wdir='C:/Users/qchat/Desktop')

  File "C:\Users\qchat\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\qchat\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/qchat/Desktop/test.py", line 8, in <module>
    to_date="15/05/2019 21:00")

  File "C:\Users\qchat\Anaconda3\lib\site-packages\trainline\__init__.py", line 547, in search
    departure_station_id = get_station_id(departure_station)

  File "C:\Users\qchat\Anaconda3\lib\site-packages\trainline\__init__.py", line 524, in get_station_id
    _STATION_DB = _station_to_dict(_STATIONS_CSV)

  File "C:\Users\qchat\Anaconda3\lib\site-packages\trainline\__init__.py", line 879, in _station_to_dict
    csv_content = _read_file(filename)

  File "C:\Users\qchat\Anaconda3\lib\site-packages\trainline\__init__.py", line 874, in _read_file
    read_data = f.read()

  File "C:\Users\qchat\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 313652: character maps to <undefined>


```

Sinon, très bonne idée ce package python :)

**Comment by tducret** [comment]
Salut @qcha41 !
Navré pour toi :(
Je n'arrive pas à reproduire ton bug sur mon PC, ou même sur cet interpréteur en ligne > https://repl.it/@tducret/trainline
Tu peux faire plus de tests?

**Comment by qcha41** [comment]
J'ai ajouté `encoding='utf-8'` dans la fonction _read_file. Je ne comprend pas pourquoi il faut spécifier l'encoding puisque utf-8 est déjà l'encoding par défaut.. mais cela à quand même résolu mon problème.

> def _read_file(filename):
>     """ Returns the file content as as string """
>     with open(filename, 'r',encoding="utf-8") as f:
>         read_data = f.read()
>     return read_data

**Comment by tducret** [comment]
Bien vu. Bizarre en tout cas.
